# COA

```{r global, echo=FALSE, include=FALSE, message = FALSE}
library(dplyr)
library(data.table)
library(DT)
library(flextable)
library(formattable)
library(glue)
library(gt)
library(here)
library(htmltools)
library(kableExtra)
library(knitr)
library(pander)
library(plotly)
library(stargazer)
library(stringr)
library(treemapify)
library(xtable)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r 2.0-rdsInput, echo=FALSE}
# -----------------------------------------------------------------------------
c_pie_grad_non        <- readRDS(here::here("/rds", "c_pie_grad_non.rds"))
c_pie_grad_res        <- readRDS(here::here("/rds", "c_pie_grad_res.rds"))
# -----------------------------------------------------------------------------
currentAY             <- readRDS(here::here("/rds", "currentAY.rds"))
dtCOA                 <- readRDS(here::here("/rds", "dtCOA.rds"))
dtCOAprior            <- readRDS(here::here("/rds", "dtCOAprior.rds"))
# -----------------------------------------------------------------------------
grad_non              <- readRDS(here::here("/rds", "grad_non.rds"))
grad_res              <- readRDS(here::here("/rds", "grad_res.rds"))
grad_non_pie          <- readRDS(here::here("/rds", "c_pie_grad_non.rds"))
grad_res_pie          <- readRDS(here::here("/rds", "c_pie_grad_res.rds"))
# -----------------------------------------------------------------------------
pdf2                  <- readRDS(here::here("/rds", "pdf2.rds"))
pdf_tbl               <- readRDS(here::here("/rds", "pdf_tbl.rds"))
```

## COA Tables

### Example one - flextable

```{r 2.1.1-coa-flextable, echo=FALSE, fig.cap='flextable', message = FALSE}
 ft <- flextable(dtCOA)
#       colkeys = c(
#             "ay2009-10",
#             "ay2010-11",
#             "ay2011-12",
#             "ay2012-13",
#             "ay2013-14",
#             "ay2014-15",
#             "ay2015-16",
#             "ay2016-17",
#             "ay2017-18",
#             "ay2018-19"
#             )
# ft <- colformat_num(
#   x = ft,
#   col_keys = colkeys,
#   big.mark = ",",
#   digits = 2,
#   na_str = "N/A")
# ft <- autofit(ft)
ft <- fit_to_width(ft, max_width = 8)
ft
```

<!-- ## Example three - formattable -->

<!-- ```{r 2.3-coa-formattable, fig.cap='formattable', out.width = '50%'} -->
<!-- formattable(dtCOA) -->
<!-- ``` -->

<!-- ## Example four - stargazer -->

<!-- ```{r 2.4-coa-stargazer, echo=FALSE, fig.cap='stargazer',  message = FALSE, out.width = '60%'} -->
<!-- stargazer(dtCOA) -->
<!-- ``` -->

<!-- ## Example five - plain ole dtCOA -->

<!-- ```{r 2.5-coa-DT-redeux, , fig.cap='plain dtCOA', out.width = '50%'} -->
<!-- dtCOA -->
<!-- ``` -->

<!-- ## Example six - DT -->

<!-- ```{r 2.6-coa-DT, fig.cap='DT', out.width = '150%'} -->
<!-- names(dtCOA)[2:11]<-letters[1:10] -->
<!-- DT::datatable(dtCOA, -->
<!--     rownames = FALSE, -->
<!--     extensions = c("Scroller"), -->
<!--     options = list( -->
<!--       pageLength = 20 -->
<!--       ,order = list(list(0, "desc")) -->
<!--       ,scrollX = TRUE -->
<!--       ,scrollY = 280 -->
<!--       ,scroller = TRUE) -->
<!--     )%>% -->
<!--     formatCurrency(c( -->
<!--       "a", "b", "c", "d", "e", "f", "g", "h", "i", "j" -->
<!--     )) -->
<!-- ``` -->

### Example two - gt

```{r 2.1.2-coa-gt, fig.cap='gt', fig.align='left', out.width = '70%'}
# names(dtCOA)[2:11]<-letters[1:10]
gt_tab_1 <-
  dtCOA %>%
    gt() %>%
    tab_header(
      title = "COA",
      subtitle = glue::glue("Undergrad")
    )
  gt_tab_2 <-
    gt_tab_1 %>%
    tab_options(
      heading.title.font.size = "small",
      heading.subtitle.font.size = "small",
      table.width = pct(20),
      table.background.color = "lightcyan",
      row.padding = px(2)
  )

  gt_tab_2
# ) %>%
#  fmt_currency(
#    columns = vars("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
#            "ay2009-10",
#            "ay2010-11",
#            "ay2011-12",
#            "ay2012-13",
#            "ay2013-14",
#            "ay2014-15",
#            "ay2015-16",
#            "ay2016-17",
#            "ay2017-18",
#            "ay2018-19"),
#    currency = "USD"
#  )
```
### Example three - kable
```{r 2.1.3.a-coa-kable, fig.cap='kable'}
kable(dtCOA)
```

```{r 2.1.3.b-coa-kable, fig.cap='kableExtra'}
kableExtra::kable(dtCOA)
```

### Example four - xtable

```{r 2.7-coa-xtable, fig.cap='xtable'}
print.xtable(dtCOA, booktabs = TRUE)
```

## COA Charts
```{r 2.2.1-coa-non}
ggplot(grad_non) +
 aes(x = Description, weight = ay1920) +
 geom_bar(fill = "#0c4c8a") +
 labs(x = "Description", y = "Amount", title = "Grad Non-Resident Expenses", subtitle = "AY 1920", caption = "Graduate Non-Resident") +
 theme_minimal()
```

```{r 2.2.2-coa-res, fig.cap='coa-res'}
ggplot(grad_res) +
 aes(x = Description, weight = ay1920) +
 geom_bar(fill = "#0c4c8a") +
 labs(x = "Description", y = "Amount", title = "Grad Resident Expenses", subtitle = "AY 1920") +
 theme_gray()
```

```{r 2.2.3-coa-non, fig.cap='coa-grad-non-pie'}
bp<- ggplot(grad_non, aes(x="", y=ay1920, fill=Description))+
    geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)
pie
```

```{r 2.2.4-coa-non, fig.cap='coa-grad-non-treemap'}
ggplot(grad_non, aes(area = ay1920, fill = ay1920, label = Description)) +
    geom_treemap() +
    geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                      grow = TRUE)
```
```{r 2.2.5-coa-res, fig.cap='coa-grad-res-treemap'}
ggplot(grad_res, aes(area = ay1920, fill = ay1920, label = Description)) +
    geom_treemap() +
    geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                      grow = TRUE)
```
